Tenebra_30B_Alpha01_Q2_K.gguf$:
  loader: llama.cpp
  cpu: false
  threads: 0
  threads_batch: 0
  n_batch: 512
  no_mmap: false
  mlock: false
  no_mul_mat_q: false
  n_gpu_layers: 59
  tensor_split: ''
  n_ctx: 900
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 0
  numa: false
  no_offload_kqv: false
  tensorcores: false
